[package]
#name = "modernwarfare-cheat-rs"
name = "mwc"
version = "0.1.0"
authors = ["Ryan McCrystal <rrmccrystal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memlib = { path = "../memlib-rs" }
win_key_codes = "0.1.2"
log = { version = "*", features = ["release_max_level_info"] }
lazy_static = "*"
cxx = "0.4.2"
rand = { version = "0.7.3", features = ["small_rng"] }
anyhow = "1.0.38"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.64"
msgbox = "0.6.0"
parking_lot = "0.11.1"
window-overlay = { path = "../window-overlay" }
winutil = { path = "../winutil" }
imgui = "0.7.0"

[patch.crates-io]
winit = { path = "../window-overlay/custom-winit" }

[build-dependencies]
cxx-build = "0.4.2"
